import { defaultDefinition } from './engine/schema';

/** Built-in Reactive Resume–aligned template definitions (declarative). */
export const BUILTIN_DEFINITIONS = [
  defaultDefinition({
    id: 'azurill',
    name: 'Azurill',
    category: 'creative',
    thumb: 'Centered header + timeline two-column',
    defaultAccent: '#3b82f6',
    preview: '/templates/jpg/azurill.jpg',
    builtin: true,
    layout: { type: 'columns', sidebarWidth: 32, padding: '12mm 14mm' },
    header: { style: 'centered', nameSize: 24, showPhoto: true, photoSize: 70, photoRadius: 8, photoBorder: true, contacts: 'row-center' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'bars',
      timeline: true,
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'certifications', 'awards', 'languages'],
    },
  }),
  defaultDefinition({
    id: 'bronzor',
    name: 'Bronzor',
    category: 'classic',
    thumb: 'Title column beside content rows',
    defaultAccent: '#334155',
    preview: '/templates/jpg/bronzor.jpg',
    builtin: true,
    layout: { type: 'bronzor', padding: '14mm 16mm' },
    header: { style: 'centered', nameSize: 24, showPhoto: true, photoSize: 64, photoRadius: 8, contacts: 'row-center' },
    sections: {
      heading: 'left-underline',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'chikorita',
    name: 'Chikorita',
    category: 'creative',
    thumb: 'Main + solid accent sidebar',
    defaultAccent: '#10b981',
    preview: '/templates/jpg/chikorita.jpg',
    builtin: true,
    layout: { type: 'sidebar-right', sidebarWidth: 34, sidebarTone: 'accent' },
    header: { style: 'photo-left', nameSize: 22, showPhoto: true, photoSize: 64, photoRadius: 999, photoBorder: true, contacts: 'row' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'bars',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications', 'hobbies'],
    },
  }),
  defaultDefinition({
    id: 'ditgar',
    name: 'Ditgar',
    category: 'modern',
    thumb: 'Tinted sidebar with accent header',
    defaultAccent: '#0f766e',
    preview: '/templates/jpg/ditgar.jpg',
    builtin: true,
    layout: { type: 'ditgar', sidebarWidth: 34 },
    header: { style: 'centered', nameSize: 18, showPhoto: true, photoSize: 68, photoRadius: 8, contacts: 'column' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'bars',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications'],
    },
  }),
  defaultDefinition({
    id: 'ditto',
    name: 'Ditto',
    category: 'minimal',
    thumb: 'Accent header band + two columns',
    defaultAccent: '#475569',
    preview: '/templates/jpg/ditto.jpg',
    builtin: true,
    layout: { type: 'columns', sidebarWidth: 30 },
    header: { style: 'band', nameSize: 24, showPhoto: true, photoSize: 70, photoRadius: 8, contacts: 'row' },
    sections: {
      heading: 'left-underline',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications', 'hobbies'],
    },
  }),
  defaultDefinition({
    id: 'gengar',
    name: 'Gengar',
    category: 'creative',
    thumb: 'Tinted sidebar, accent header block',
    defaultAccent: '#7c3aed',
    preview: '/templates/jpg/gengar.jpg',
    builtin: true,
    layout: { type: 'ditgar', sidebarWidth: 34 },
    header: { style: 'centered', nameSize: 18, showPhoto: true, photoSize: 68, photoRadius: 999, contacts: 'column' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'bars',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications', 'hobbies'],
    },
  }),
  defaultDefinition({
    id: 'glalie',
    name: 'Glalie',
    category: 'classic',
    thumb: 'Light sidebar with contact box',
    defaultAccent: '#64748b',
    preview: '/templates/jpg/glalie.jpg',
    builtin: true,
    layout: { type: 'sidebar-left', sidebarWidth: 34, sidebarTone: 'muted' },
    header: { style: 'sidebar-top', nameSize: 18, showPhoto: true, photoSize: 68, photoRadius: 8, contacts: 'column' },
    sections: {
      heading: 'left-underline',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications', 'hobbies'],
    },
  }),
  defaultDefinition({
    id: 'kakuna',
    name: 'Kakuna',
    category: 'classic',
    thumb: 'Centered header & accent section titles',
    defaultAccent: '#b45309',
    preview: '/templates/jpg/kakuna.jpg',
    builtin: true,
    layout: { type: 'single', padding: '14mm 16mm' },
    header: {
      style: 'centered',
      nameFont: 'serif',
      nameSize: 26,
      showPhoto: true,
      photoSize: 72,
      photoRadius: 10,
      photoBorder: true,
      contacts: 'row-center',
    },
    sections: {
      heading: 'center-underline',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages', 'awards', 'hobbies'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'lapras',
    name: 'Lapras',
    category: 'executive',
    thumb: 'Card sections with overlapping titles',
    defaultAccent: '#1e3a8a',
    preview: '/templates/jpg/lapras.jpg',
    builtin: true,
    layout: { type: 'cards', padding: '14mm 16mm' },
    header: { style: 'card', nameSize: 22, showPhoto: true, photoSize: 64, photoRadius: 12, contacts: 'row' },
    sections: {
      heading: 'left-underline',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'leafish',
    name: 'Leafish',
    category: 'modern',
    thumb: 'Tinted intro band + two columns',
    defaultAccent: '#059669',
    preview: '/templates/jpg/leafish.jpg',
    builtin: true,
    layout: { type: 'columns', sidebarWidth: 32 },
    header: { style: 'leafish', nameSize: 22, showPhoto: true, photoSize: 72, photoRadius: 8, contacts: 'row' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'bars',
      main: ['experience', 'education', 'projects'],
      sidebar: ['skills', 'languages', 'certifications', 'hobbies'],
    },
  }),
  defaultDefinition({
    id: 'meowth',
    name: 'Meowth',
    category: 'classic',
    thumb: 'Uppercase titles, inline entry headers',
    defaultAccent: '#b45309',
    preview: '/templates/jpg/meowth.jpg',
    builtin: true,
    layout: { type: 'single', padding: '14mm 16mm' },
    header: { style: 'photo-right', nameSize: 24, showPhoto: true, photoSize: 72, photoRadius: 6, contacts: 'row' },
    sections: {
      heading: 'uppercase',
      experienceHeader: 'inline',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'onyx',
    name: 'Onyx',
    category: 'modern',
    thumb: 'Header rule, clean single column',
    defaultAccent: '#1d4ed8',
    preview: '/templates/jpg/onyx.jpg',
    builtin: true,
    layout: { type: 'single', padding: '14mm 16mm' },
    header: { style: 'photo-left', nameSize: 24, showPhoto: true, photoSize: 68, photoRadius: 8, contacts: 'row' },
    sections: {
      heading: 'plain',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages', 'awards'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'pikachu',
    name: 'Pikachu',
    category: 'creative',
    thumb: 'Sidebar + accent header panel',
    defaultAccent: '#ca8a04',
    preview: '/templates/jpg/pikachu.jpg',
    builtin: true,
    layout: { type: 'pikachu', sidebarWidth: 30 },
    header: { style: 'panel', nameFont: 'serif', nameSize: 22, showPhoto: true, photoSize: 80, photoRadius: 10, contacts: 'row' },
    sections: {
      heading: 'left-underline',
      skillsDisplay: 'dots',
      main: ['summary', 'experience', 'education', 'projects'],
      sidebar: ['certifications', 'hobbies', 'awards', 'skills', 'languages'],
    },
  }),
  defaultDefinition({
    id: 'rhyhorn',
    name: 'Rhyhorn',
    category: 'minimal',
    thumb: 'Pipe contacts, generous whitespace',
    defaultAccent: '#0ea5e9',
    preview: '/templates/jpg/rhyhorn.jpg',
    builtin: true,
    layout: { type: 'single', padding: '18mm 18mm' },
    header: { style: 'photo-right', nameSize: 26, showPhoto: true, photoSize: 76, photoRadius: 8, contacts: 'pipes' },
    sections: {
      heading: 'left-underline',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages'],
      sidebar: [],
    },
  }),
  defaultDefinition({
    id: 'scizor',
    name: 'Scizor',
    category: 'executive',
    thumb: 'Top accent stripe, uppercase headings',
    defaultAccent: '#dc2626',
    preview: '/templates/jpg/scizor.jpg',
    builtin: true,
    layout: { type: 'scizor', padding: '12mm 16mm', topStripe: true },
    header: { style: 'photo-right', nameSize: 28, showPhoto: true, photoSize: 72, photoRadius: 6, contacts: 'row' },
    sections: {
      heading: 'scizor',
      main: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'languages'],
      sidebar: [],
    },
  }),
];

export const DEFINITION_MAP = Object.fromEntries(BUILTIN_DEFINITIONS.map((d) => [d.id, d]));

export const LEGACY_TEMPLATE_ALIASES = {
  modern: 'azurill',
  midnight: 'ditgar',
  arctic: 'leafish',
  classic: 'kakuna',
  minimal: 'rhyhorn',
  professional: 'lapras',
  creative: 'chikorita',
  executive: 'scizor',
  harmony: 'bronzor',
  zen: 'bronzor',
  block: 'pikachu',
};
